### ISSUE TITLE
Output missing from Module

### ISSUE THREAD

**Issue by TheCreativeMind** [awslabs/keras-apache-mxnet#118]
Hello,

I am currently building a cnn model with keras and mxnet, but mxnet keeps complaining that there is no output with such a name...

First I get a userWarning 
` You created Module with Module(..., label_names=['/xyz_pred_loss_target1', '/xyz_pred_loss_sample_weights1']) but input with name '/xyz_pred_loss_target1' is not found in symbol.list_arguments(). Did you mean one of:
...`

Followed by an Error: 
`KeyError: 'xyz_pred_loss_target1'`

The 'xyz_pred_loss_sample_weights1' are listed in symbol_list_arguments... The target, as the keyError suggests is not.

I am using a custom loss function calculated in a similar fashion like the ctc loss in the example [https://github.com/awslabs/keras-apache-mxnet/blob/master/examples/image_ocr.py](https://github.com/awslabs/keras-apache-mxnet/blob/master/examples/image_ocr.py)

I have no Idea, why my model crashes at this point...

**Comment by kalyc** [comment]
Thanks for submitting this issue @TheCreativeMind 
Could you share minimum code for reproducing this error? Are you saving the model?

@roywei could you add label "Pending Requester Info" to this?

**Comment by kalyc** [comment]
Hi @TheCreativeMind 
Closing this issue at the moment. Please feel free to comment and re-open the issue and add further details.
