### ISSUE TITLE
change CI for PR to track dev branch

### ISSUE THREAD

**Issue by roywei** [awslabs/keras-apache-mxnet#123]
Currently CI job for PR track master branch, we should change it to dev branch.

**Comment by roywei** [comment]
Once #148 merged, change CodeBuild to read from `keras_mxnet_ci/nightly-buildspec.yml` and `keras_mxnet_ci/pr-buildspec.yml `

**Comment by kalyc** [comment]
Closing issue as the CI build has been enabled
