### ISSUE TITLE
keras-mxnet pypi install keras-team/keras>=2.1.6

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [awslabs/keras-apache-mxnet#129]
When you pypi install `keras-mxnet`, it install `keras`, this can create conflicts. 

Reason: keras-preprocessing / keras-applications declares dependency on `keras` - https://github.com/keras-team/keras-preprocessing/blob/master/setup.py#L33

**Comment by roywei** [comment]
Thanks for this catch!
currently keras is installed as dependency of keras-applications/keras-preprocessing, and keras-mxnet installation will override keras. For now, users won't see a difference but it could cause potential conflict in future.

Possible solutions:
1. try to ignore keras dependency in pypi configuration, so keras will not be installed during keras-application/preprocess installation.

2. Use keras-applications/preprocessing as git submodules, and remove dependency in keras-mxnet pypi config.

**Comment by roywei** [comment]
might be related:
https://stackoverflow.com/questions/51092421/keras-mxnet-not-pulling-properly-from-pip

**Comment by roywei** [comment]
Right now, as keras-mxnet will override keras pip package during installation, there is no impact on user side. everything works fine. Ideally we need to remove the official keras pip install step.

**Comment by roywei** [comment]
fixed in https://github.com/keras-team/keras/issues/11243
