### ISSUE TITLE
module 'keras.models' has no attribute 'save_mxnet_model'

### ISSUE THREAD

**Issue by Robchio** [awslabs/keras-apache-mxnet#152]
Hey gang - I've carefully uninstalled Keras, installed keras-apache-mxnet v. 2.1.5, altered the keras.json, loaded Keras and gotten the message "Using MXNet backend"

I've successfully trained my model, and model.save('test.h5') seems to work...

However, the following code throws and error
k.models.save_mxnet_model(model=model, prefix='1d_Convo_model_2018-0809')

AttributeError: module 'keras.models' has no attribute 'save_mxnet_model'

print(k.__version__)
2.1.5
What am I missing? 

Am I somehow not actually using keras-apache-mxnet?

**Comment by Robchio** [comment]
https://github.com/awslabs/keras-apache-mxnet/blob/master/docs/mxnet_backend/save_mxnet_model.md

**Comment by kalyc** [comment]
Hi @Robchio thanks for opening this issue. 
`save_mxnet_model` is supported in [keras-mxnet v2.1.6](https://github.com/awslabs/keras-apache-mxnet/releases/tag/v2.1.6)
Would recommend uninstalling & re-installing keras-mxnet as follows:

```
# Uninstall any previous keras
pip uninstall keras

# Uninstall keras-mxnet 
pip uninstall keras-mxnet

# Install Keras2 with MXNet
pip install keras-mxnet
```

If this doesn't work, could let us know which OS & Python version is being used?

**Comment by Robchio** [comment]
ok, troubleshooting now - I had previously installed keras-apache-mxnet - thanks for the clarification!

**Comment by Robchio** [comment]
This resolved my issue, thanks for the fast response!

In order to get this to work, I ALSO had to delete ~/.keras/keras.json
