### ISSUE TITLE
multi-gpu tutorial: model parameter (n and version)

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/keras-apache-mxnet#43]
The comments say that if we're doing ResNet110 - which I think we are - then `n` should be set to 18 or 12, depending on what version we're running. We're still running `n=3` which is ResNet20.0 on version 1. Also, should be we be running version 2 instead of 1?

**Comment by sandeep-krishnamurthy** [comment]
This is issue is now fixed with new benchmark module - https://github.com/awslabs/keras-apache-mxnet/blob/master/benchmark/scripts/benchmark_resnet.py
