### ISSUE TITLE
Fail to install keras with Mxnet

### ISSUE THREAD

**Issue by harryprince** [awslabs/keras-apache-mxnet#57]
I am trying to install keras with mxnet,  howerver, it failed.

```
pip install git+https://github.com/awslab
s/keras-apache-mxnet

  File "/tmp/RtmpIpKgN0/chunk-code-26bb3d563203.txt", line 1, in <module>
    import keras
  File "/home/mobike-gpu-server-1/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/mobike-gpu-server-1/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/mobike-gpu-server-1/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/mobike-gpu-server-1/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/keras/backend/__init__.py", line 36, in <module>
    assert _backend in {'theano', 'tensorflow', 'cntk'}
AssertionError
```

My environment:
```
Ubuntu 16.04.4 LTS \n \l
python 2.7.12
cuda9.1
mxnet-cu91
```

**Comment by sandeep-krishnamurthy** [comment]
@harryprince - MXNet backend code is still in a branch - "keras2_mxnet_backend". I am working on merging it to master. In the mean time, you need to use commands in below wiki to install from source on the branch.

https://github.com/awslabs/keras-apache-mxnet/wiki/Installation-Guide---Keras-with-MXNet-backend

**Comment by sandeep-krishnamurthy** [comment]
@harryprince - Please reopen the issue if the installation is still failing.

**Comment by harryprince** [comment]
@sandeep-krishnamurthy installation seems work, however, import keras got some error, and someone faced the same issue:

https://stackoverflow.com/questions/45060150/keras-cannot-import-name-np-utils

**Comment by sandeep-krishnamurthy** [comment]
@harryprince - I have seen that issue, when you have previous installed Keras1.2 and then you install Keras2.
Can you please uninstall all existing keras versions and re-install keras2 with mxnet? Below are the commands:
```
pip uninstall keras
pip uninstall keras-mxnet

pip install git+https://github.com/awslabs/keras-apache-mxnet.git@keras2_mxnet_backend --user
```

**Comment by aglaiawong** [comment]
> # Uninstall any previous keras
> pip uninstall keras
> 
> # Uninstall keras-mxnet (keras1.2 with mxnet) if you have previously installed
> pip uninstall keras-mxnet
> 
> # Install Keras2 with MXNet
> pip install git+https://github.com/awslabs/keras-apache-mxnet.git@keras2_mxnet_backend --user

this one not working neither. I was testing on amz ec2 instance this fails.
