### ISSUE TITLE
K.gather not working for Embedding Layer using MXNet backend

### ISSUE THREAD

**Issue by roywei** [awslabs/keras-apache-mxnet#63]
In Keras Embedding layer, K.gather operator is used (MXNet backend use mx.sym.take and TensorFlow backend use tf.gather for implementation). However, K.gather is giving error when using MXNet backend, and this issue only occurs in Embedding layer use case, not in other use cases.
**Test Case**:
 tests/keras/layers/embeddings_test.py
**Error Message**:
`Error in operator broadcast_mul0: [13:05:25] src/operator/tensor/./elemwise_binary_broadcast_op.h:67: Check failed: l == 1 || r == 1 operands could not be broadcast together with shapes [3,2] [3]
`
This [PR](https://github.com/awslabs/keras-apache-mxnet/pull/61) fixed it and is using directly mx.sym.Embedding instead of K.gather to implement the Keras Embedding Layer. Note this fix will break original Keras code and have conflict in future merge.

**Comment by sandeep-krishnamurthy** [comment]
Closing in favor of - https://github.com/awslabs/keras-apache-mxnet/issues/18
