### ISSUE TITLE
Does not utilize all the GPUs on a multi-gpu machine

### ISSUE THREAD

**Issue by karan6181** [awslabs/keras-apache-mxnet#67]
Hello,

I have noticed that while running `keras/example/cifar10_cnn.py`(uses Sequential API) and `keras/example/lstm_text_generation.py`(uses Sequential API)  on multi-gpu machine such as Amazon AWS P3.8xLarge instance, the code does not utilize all the GPUs. However, it just uses a single GPU.

I have used `keras-apache-mxnet/benchmark` template scripts and modified `cifar10_cnn.py` and `lstm_text_generation.py` based on that template script.

**Command:**

```bash
sh run_mxnet_backend.sh 4_gpu_config
```

Here, the test is only using 1 GPU instead of 4 GPUs.

However, the when I ran the `benchmark_resnet.py(uses functional API) ` test with `4_gpu_config` option, it utilizes all the GPUs. 

I think the problem is with setting the model context when test uses keras `sequential()` API. 

**More information:**

```bash
(Pdb) self
<keras.models.Sequential object at 0x7f3002ad9630>

(Pdb) self._context
[gpu(0), gpu(1), gpu(2), gpu(3)]

(Pdb) self.model
<keras.backend.mxnet_backend.get_model.<locals>.Model object at 0x7f2ffb4ec9b0>

(Pdb) self.model._context
[gpu(0)]
```

Thank-You.

**Comment by roywei** [comment]
Great catch, thank you for this finding. Luckily current benchmarks use cifar10 resnet and imagenet resnet. The scripts use functional API to create the model instead of Sequential(). We need this to be fixed for adding RNN benchmarks.

**Comment by spidyDev** [comment]
@karan6181  Please close this issue if its fixed.

**Comment by karan6181** [comment]
Closing this issue since it's fixed.
