### ISSUE TITLE
errors when installing keras-mxnet in python 2.7 mxnet conda env

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/keras-apache-mxnet#87]
Using a DLAMI Ubuntu v7 in the mxnet_p27 Conda environment I get the following errors after running `pip install --upgrade h5py numpy keras-mxnet`:

```
mkl-random 1.0.1 requires cython, which is not installed.
mkl-fft 1.0.0 requires cython, which is not installed.
botocore 1.10.2 has requirement python-dateutil<2.7.0,>=2.1, but you'll have python-dateutil 2.7.2 which is incompatible.
mxnet-cu90mkl 1.1.0 has requirement numpy<=1.13.3, but you'll have numpy 1.14.3 which is incompatible.
```

The mxnet_p36 env works fine.

**Comment by kalyc** [comment]
DLAMI supports Keras-MXNet now so manual installation is not needed anymore. You can directly use keras as its pre-installed in the DLAMI environment. 

Tested on both `mxnet_p27` and `mxnet_p36` environment

Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using MXNet backend

Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using MXNet backend
