### ISSUE TITLE
fix need in docs

### ISSUE THREAD

**Issue by roywei** [awslabs/keras-apache-mxnet#88]
benchmark script:
https://github.com/awslabs/keras-apache-mxnet/tree/dev/benchmark
dash missing for layers param
/ missing for data path
it should be:
```
python benchmark_resnet.py --dataset imagenet --version 1 --layers 56 --gpus 8 --epoch 20 --train_mode train_on_batch --data_path /home/ubuntu/imagenet/train
```

**Comment by sandeep-krishnamurthy** [comment]
done - https://github.com/awslabs/keras-apache-mxnet/pull/82
